# Cloudflare Workers設定ファイル
# プロダクション環境でD1データベースを使用するための設定

name = "saifuu"
compatibility_date = "2025-06-23"
main = "./build/server/index.js"

# D1データベース設定（プロダクション環境用）
[[d1_databases]]
binding = "DB"
database_name = "saifuu-db"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # 実際のデプロイ時に設定

# 環境変数
[vars]
NODE_ENV = "production"

# 開発環境設定
[env.development]
vars = { NODE_ENV = "development" }

# ステージング環境設定
[env.staging]
vars = { NODE_ENV = "staging" }