# セルフホストランナー用CI/CDワークフロー
# 軽量ジョブ（型チェック、リント、ユニットテスト、ビルド）を統合実行
#
# 設計判断：
# - セルフホストランナーで高速実行、GitHub Actions無料枠を節約
# - E2Eテストは別途GitHub hosted runnerで実行
# - 統合ジョブによりセットアップ時間を削減（issue #80対応）
# - 早期失敗により無駄なリソース使用を回避
# - 適切なファイル変更トリガーで無駄な実行を回避

name: CI Self-Hosted

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.md'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.storybook/**'
      - 'vite.config.ts'
      - 'tailwind.config.ts'
      - 'biome.json'
      - 'tsconfig.json'
      - '.github/workflows/ci-selfhosted.yml'
      # check.ymlの削除により重複実行を防止
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  # 統合ジョブ：型チェック、リント、ユニットテスト、ビルドを順次実行
  # セットアップ時間を削減し、早期失敗によりリソースを効率的に使用
  ci:
    runs-on: [self-hosted, linux]
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install pnpm manually
        run: npm install -g pnpm@10
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # ステップ1: 型チェックとリント（最も高速、早期フィードバック）
      - name: Run type checking and linting
        run: pnpm run check
      
      # ステップ2: ユニットテスト（型チェック通過後のみ実行）
      - name: Run unit tests
        run: pnpm test:unit:coverage
        env:
          CI: true
          NODE_ENV: test
      
      # ステップ3: アプリケーションビルド（全テスト通過後のみ実行）
      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production

      # ユニットテスト結果をPRにコメント投稿（統合ジョブの最後に実行）
      - name: Post test results to PR
        if: github.event_name == 'pull_request'
        run: ./scripts/coverage-comment.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_NUMBER: ${{ github.event.number }}
      

  # Storybookビルド（一時的に無効化 - React Router競合対応中）
  # storybook:
  #   runs-on: [self-hosted, linux]
  #   timeout-minutes: 15
  #   
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     
  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: '10'
  #         standalone: true
  #     
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'
  #         cache: 'pnpm'
  #     
  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile
  #     
  #     - name: Build Storybook
  #       run: pnpm run build-storybook
  #       env:
  #         NODE_ENV: production
  #     
  #     - name: Upload Storybook artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: storybook-static
  #         path: storybook-static/
  #         retention-days: 7

